#!/usr/bin/env python3
"""gen_tables.py — offline table generator for the c2tube fixed-point decoder.

Float is allowed HERE (build-time, host-side); the emitted tables are pure
integers.  Single source of truth: emits both c2tube_tables.h (for the C
decoder) and tables.py (for golden.py) from the same computed values, so the
two implementations cannot drift.

Tables
------
  LSP_CB[10][..]   scalar LSP codebooks, int16 Hz, read verbatim from the
                   pinned codec2 checkout (build/codec2/src/codebook/lsp*.txt;
                   values are integer Hz in the upstream text files).
                   Bit widths per index: 4,4,4,4,4,4,4,3,3,2 (=36 bits/frame,
                   codec2.c codec2_encode_1300 lines 1077-1124).
  LG2E_Q8[32]      decoded frame energy in log2 domain, Q8:
                   E_dB = -10 + (50/32)*index  (quantise.c decode_energy
                   lines 934-946, E_MIN_DB=-10 E_MAX_DB=40 quantise.h:38-39),
                   lg2(e) = E_dB * log2(10)/10.
  COS_Q14[251]     cos(pi*f/4000) for f = 0,16,...,4000 Hz, Q14; runtime does
                   linear interpolation on the low 6 bits of f_q2 (quarter-Hz).
  EXP2_Q14[33]     2^(i/32), Q14 (uint16; 2^1.0 -> 32768 fits uint16).
  LOG2_Q8[33]      log2(1+i/32), Q8.
  Mixed-excitation crossover at 2500 Hz (tube-ladder REPORT.md verdict:
  "кроссовер 2.5 кГц — лучший компромисс"): power-complementary 2nd-order
  Butterworth LP/HP, Q14 coefficient sets B_LP,A_LP,B_HP,A_HP.
  G1POW_Q14[11], G2POW_Q14[11]   0.65^k and 0.8^k for the folded postfilter
  A(z/0.65)/A(z/0.8) (tube-ladder L4, gamma1 in the measured-best 0.5..0.65
  range, gamma2=0.8).
"""
import os
import numpy as np
from scipy.signal import butter

HERE = os.path.dirname(os.path.abspath(__file__))
CB_DIR = os.path.join(HERE, "build", "codec2", "src", "codebook")

LSP_BITS = [4, 4, 4, 4, 4, 4, 4, 3, 3, 2]


def read_codebooks():
    cbs = []
    for i in range(1, 11):
        path = os.path.join(CB_DIR, f"lsp{i}.txt")
        with open(path) as f:
            hdr = f.readline().split()
            k, m = int(hdr[0]), int(hdr[1])
            vals = [float(x) for x in f.read().split()]
        assert k == 1 and len(vals) == m, (path, k, m, len(vals))
        assert m == (1 << LSP_BITS[i - 1]), (path, m)
        ints = [int(round(v)) for v in vals]
        for v, vi in zip(vals, ints):
            assert v == vi, f"{path}: non-integer Hz value {v}"
        cbs.append(ints)
    return cbs


def q(x, s):
    return int(round(x * (1 << s)))


def main():
    cbs = read_codebooks()

    lg2e = [q((-10.0 + (50.0 / 32) * i) * np.log2(10) / 10.0, 8)
            for i in range(32)]

    cos_q14 = [q(np.cos(np.pi * (16 * i) / 4000.0), 14) for i in range(251)]
    # clamp the |c|<1 box (quantise_lsp_csd C_CLAMP = 1 - 2^-10, redteam
    # engines_rt.py:659); table endpoints are +/-16384, runtime clamps anyway
    exp2_q14 = [q(2.0 ** (i / 32.0), 14) for i in range(33)]
    log2_q8 = [q(np.log2(1.0 + i / 32.0), 8) for i in range(33)]

    b_lp, a_lp = butter(2, 2500.0 / 4000.0, "low")
    b_hp, a_hp = butter(2, 2500.0 / 4000.0, "high")
    blp = [q(v, 14) for v in b_lp]
    alp = [q(v, 14) for v in a_lp]
    bhp = [q(v, 14) for v in b_hp]
    ahp = [q(v, 14) for v in a_hp]

    g1p = [q(0.65 ** k, 14) for k in range(11)]
    g2p = [q(0.80 ** k, 14) for k in range(11)]

    # ---------------- emit C header ----------------
    def carr(name, ctype, vals, per=12):
        lines = [f"static const {ctype} {name}[{len(vals)}] = {{"]
        for j in range(0, len(vals), per):
            lines.append("    " + ", ".join(str(v) for v in vals[j:j + per]) + ",")
        lines.append("};")
        return "\n".join(lines)

    hdr = ["/* AUTO-GENERATED by gen_tables.py — do not edit. */",
           "#ifndef C2TUBE_TABLES_H", "#define C2TUBE_TABLES_H",
           "#include <stdint.h>", ""]
    hdr.append("static const uint8_t LSP_BITS_TAB[10] = {" +
               ", ".join(str(b) for b in LSP_BITS) + "};")
    flat = [v for cb in cbs for v in cb]
    offs, o = [], 0
    for cb in cbs:
        offs.append(o)
        o += len(cb)
    hdr.append(carr("LSP_CB_FLAT", "int16_t", flat))
    hdr.append("static const uint8_t LSP_CB_OFF[10] = {" +
               ", ".join(str(v) for v in offs) + "};")
    hdr.append(carr("LG2E_Q8", "int16_t", lg2e))
    hdr.append(carr("COS_Q14", "int16_t", cos_q14))
    hdr.append(carr("EXP2_Q14", "uint16_t", exp2_q14))
    hdr.append(carr("LOG2_Q8", "uint16_t", log2_q8))
    hdr.append(carr("B_LP_Q14", "int16_t", blp))
    hdr.append(carr("A_LP_Q14", "int16_t", alp))
    hdr.append(carr("B_HP_Q14", "int16_t", bhp))
    hdr.append(carr("A_HP_Q14", "int16_t", ahp))
    hdr.append(carr("G1POW_Q14", "int16_t", g1p))
    hdr.append(carr("G2POW_Q14", "int16_t", g2p))
    hdr.append("")
    hdr.append("#endif /* C2TUBE_TABLES_H */")
    with open(os.path.join(HERE, "c2tube_tables.h"), "w") as f:
        f.write("\n".join(hdr) + "\n")

    # ---------------- emit python twin ----------------
    py = ["# AUTO-GENERATED by gen_tables.py — do not edit.",
          f"LSP_BITS = {LSP_BITS!r}",
          f"LSP_CB = {cbs!r}",
          f"LG2E_Q8 = {lg2e!r}",
          f"COS_Q14 = {cos_q14!r}",
          f"EXP2_Q14 = {exp2_q14!r}",
          f"LOG2_Q8 = {log2_q8!r}",
          f"B_LP_Q14 = {blp!r}", f"A_LP_Q14 = {alp!r}",
          f"B_HP_Q14 = {bhp!r}", f"A_HP_Q14 = {ahp!r}",
          f"G1POW_Q14 = {g1p!r}", f"G2POW_Q14 = {g2p!r}"]
    with open(os.path.join(HERE, "tables.py"), "w") as f:
        f.write("\n".join(py) + "\n")

    # flash census of the tables
    nbytes = (len(flat) * 2 + len(lg2e) * 2 + len(cos_q14) * 2 +
              len(exp2_q14) * 2 + len(log2_q8) * 2 + 4 * 3 * 2 * 2 +
              len(g1p) * 2 + len(g2p) * 2 + 10 + 10)
    print(f"tables written; .rodata payload ~= {nbytes} bytes")


if __name__ == "__main__":
    main()
